-- ============================================
-- TECHZONEUY - Esquema Supabase
-- Ejecutar en Supabase Dashboard > SQL Editor
-- ============================================

-- 1. Tabla productos (con URL de imagen en Storage)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT DEFAULT '',
  description TEXT DEFAULT '',
  price INTEGER NOT NULL DEFAULT 0,
  category TEXT NOT NULL CHECK (category IN ('airpods','auriculares','parlantes','fundas','cargadores','accesorios')),
  image TEXT DEFAULT '', -- URL pública de Supabase Storage o base64 legacy
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla pedidos
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT DEFAULT '',
  customer_phone TEXT DEFAULT '',
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pendiente' CHECK (status IN ('pendiente','completado','cancelado')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla admin (opcional, si querés migrar login)
CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL, -- hash bcrypt
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert admin inicial (password: techzone2024)
INSERT INTO public.admin_users (username, password)
VALUES ('admin', '$2y$10$CZV53.uOq/a3DVfEwgpgHeGPTG9p9YxK0vN6x8mQwEr8sX5yZ5yZ5yZ5y')
ON CONFLICT (username) DO NOTHING;

-- 4. Habilitar RLS y políticas públicas para lectura (ajustá según necesites auth)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Políticas: permitir todo a anon/service_role por ahora (podés restringir luego)
DROP POLICY IF EXISTS "Allow all for anon products" ON public.products;
CREATE POLICY "Allow all for anon products" ON public.products FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon orders" ON public.orders;
CREATE POLICY "Allow all for anon orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read admin" ON public.admin_users;
CREATE POLICY "Allow read admin" ON public.admin_users FOR SELECT USING (true);

-- 5. Storage: crear bucket 'product-images' (ejecutar también en Storage UI si falla)
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas Storage: lectura pública, escritura autenticada (anon puede subir por ahora)
DROP POLICY IF EXISTS "Public read product-images" ON storage.objects;
CREATE POLICY "Public read product-images" ON storage.objects FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Allow upload product-images" ON storage.objects;
CREATE POLICY "Allow upload product-images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Allow update product-images" ON storage.objects;
CREATE POLICY "Allow update product-images" ON storage.objects FOR UPDATE USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Allow delete product-images" ON storage.objects;
CREATE POLICY "Allow delete product-images" ON storage.objects FOR DELETE USING (bucket_id = 'product-images');

-- 6. Datos iniciales (17 productos) - opcional, si querés migrar
-- Descomenta si querés insertar desde cero:
/*
INSERT INTO public.products (name, brand, description, price, category, image) VALUES
('AirPods Pro','Apple','Disfrutá de un sonido de alta calidad con cancelación activa de ruido.',2000,'airpods','img/airpods-pro.png'),
('AirPods 4 (ANC)','Apple','Los nuevos AirPods 4 con Cancelación Activa de Ruido.',2000,'airpods','img/airpods-4-anc.png'),
('AirPods Max','Apple','Sonido potente y nítido, diseño cómodo y elegante.',2200,'airpods','img/airpods-max.png');
*/
